-- SAAC local database schema for SQLite.
-- Usage: sqlite3 saac.sqlite3 < database.sqlite.sql

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS `CSAlogin` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `username` TEXT NOT NULL UNIQUE,
  `password` TEXT NOT NULL,
  `IP` TEXT NOT NULL DEFAULT '-',
  `MAC` TEXT NOT NULL DEFAULT '',
  `RegTime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LoginTime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OnlineName` TEXT,
  `OnlineName1` TEXT,
  `OnlineName2` TEXT,
  `Online` INTEGER DEFAULT 0,
  `Path` TEXT DEFAULT '',
  `VipPoint` INTEGER DEFAULT 0,
  `PayPoint` INTEGER DEFAULT 0,
  `GamblePoint` INTEGER DEFAULT 0,
  `TrialPoint` INTEGER NOT NULL DEFAULT 0,
  `GoldPoint` INTEGER NOT NULL DEFAULT 0,
  `SQLPoint` INTEGER NOT NULL DEFAULT 0,
  `SafePasswd` TEXT DEFAULT '',
  `ServerId` INTEGER NOT NULL DEFAULT 0,
  `Regip` TEXT NOT NULL DEFAULT '',
  `qq` TEXT NOT NULL DEFAULT '',
  `tel` TEXT NOT NULL DEFAULT '',
  `ServerName` TEXT NOT NULL DEFAULT '',
  `Recommender` INTEGER NOT NULL DEFAULT 0,
  `Lock` INTEGER NOT NULL DEFAULT 0,
  `LockTime` TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LockInfo` TEXT NOT NULL DEFAULT '',
  `Offline` INTEGER NOT NULL DEFAULT 0,
  `Trust` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `LOCK` (
  `Name` TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS `OnlineCost` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `CostPasswd` TEXT NOT NULL UNIQUE,
  `CostVal` INTEGER NOT NULL DEFAULT 0,
  `PayVal` INTEGER NOT NULL DEFAULT 0,
  `check` INTEGER NOT NULL DEFAULT 1,
  `cdkey` TEXT DEFAULT '',
  `CostTime` TEXT
);

CREATE TABLE IF NOT EXISTS `OnlineBuy` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `CostPasswd` TEXT NOT NULL UNIQUE,
  `CostStr` TEXT NOT NULL,
  `check` INTEGER NOT NULL DEFAULT 1,
  `cdkey` TEXT DEFAULT '',
  `CostTime` TEXT
);
